name: Pact Contract Verification

on:
  workflow_dispatch:
    inputs:
      pact_url:
        description: 'URL of the pact to verify'
        required: true
      consumer_version_tags:
        description: 'Consumer version tags'
        required: false
        default: ''
      consumer_version_number:
        description: 'Consumer version number'
        required: false
        default: ''
      provider_version_tags:
        description: 'Provider version tags'
        required: false
        default: ''
      event_name:
        description: 'Name of the event that triggered the webhook'

permissions:
  checks: write
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      
      - name: Verify Pact
        env:
          PACT_BROKER_URL: ${{ secrets.PACT_BROKER_URL }}
          PACT_BROKER_TOKEN: ${{ secrets.PACT_BROKER_TOKEN }}
        run: ./mvnw test -Dtest=PactProviderVerificationTest

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Pact Verification Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
